#ifndef LEXER_LEXEMTYPE_H
#define LEXER_LEXEMTYPE_H

enum lexemtype {
    null, OBRA, CBRA, OPAR, CPAR, SEMICOLON, INTKW, RETURNKW, IFKW, ELSEKW, FORKW, WHILEKW,
    IDENTIFIER, EQUAL, INTLITERAL, LESS, MORE, PLUS, MINUS, MULTIPLICATION, DIVISION,
    LOGIC_NEG, DOUBLEKW, CHARKW, FLOATKW, COMMA
};

#endif //LEXER_LEXEMTYPE_H
